import os

SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET= os.getenv("SPOTIFY_CLIENT_SECRET")
SPOTIFY_REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI")

WEATHER_API_KEY = os.getenv("WEATHER_API_KEY")
def print_config():
    print(f"SPOTIFY_CLIENT_ID={SPOTIFY_CLIENT_ID}, SPOTIFY_CLIENT_SECRET={SPOTIFY_CLIENT_SECRET}, SPOTIFY_REDIRECT_URI={SPOTIFY_REDIRECT_URI},WEATHER_API_KEY={WEATHER_API_KEY}  ")